### ISSUE TITLE
Create City Guide for Austin

### ISSUE THREAD

**Issue by chefscott** [djangocon/djangocon-us-docs#13]
Create a city guide for Austin:

- [ ] Restaurants
- [ ] Bars
- [ ] Local entertainment

**Due date**: 09/04/2015

**Comment by crccheck** [comment]
I suggest doing this as an etherpad or google doc at first so it's easier for people to collaborate. I just use [mozilla's etherpad](https://etherpad.mozilla.org/) when I want one.

**Comment by jefftriplett** [comment]
Fantastic idea! Are you volunteering to help? We've also used google docs pretty extensively.

**Comment by crccheck** [comment]
sure thing. I know many locals have already made suggestions in the google group. If there's existing collaboration in google docs, then let's do that. Can you create the document and paste the share url in this issue?

**Comment by jefftriplett** [comment]
I think most are reflected here in the repo: https://github.com/djangocon/djangocon-us-docs/blob/master/foodndrink.yml but there is no real editorial overview which is also what we need. We are at the AT&T Executive Education and Conference Center (1900 University Ave.) if that helps to pinpoint a general location / region. 

Here is a Google Doc to start with: https://docs.google.com/document/d/1ewFuAo6mP57hCJ67PNHDgeffpjSMt-D_tGOs3R6CdcQ/edit?usp=sharing

**Comment by crccheck** [comment]
at this point, I think the Google Doc has the most information. Let's set a deadline to run it by more locals to come up with a curated list. My thought is to make it 70% things that are walkable (about a mile), 20% notable but close (3 miles), and 10% for the rest.

**Comment by jefftriplett** [comment]
Hey Chris, if you are still interested in helping out please contact me via my email address on my github profile / commits and I'll get you added to Trello. We are managing everything form Trello and it's scaling much better than github issues for us. Thanks for all fo the work that you did on this!
