### ISSUE TITLE
Refresh Twitter Avatar and Background

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon-us-docs#24]
We need new images for our twitter account: https://twitter.com/djangocon

**Comment by jefftriplett** [comment]
Hey @mightym is this something you can help with?

**Comment by chefscott** [comment]
@jefftriplett this is already in #21 -- would you like these to be broken out more?

**Comment by jefftriplett** [comment]
In this case one feels like a role whereas the graphics are a one-time creation.

**Comment by craigbruce** [comment]
https://twitter.com/djangocon Looks good!
