### ISSUE TITLE
Review Code of Conduct and all policies

### ISSUE THREAD

**Issue by jefftriplett** [djangocon/djangocon-us-docs#25]
Our Code of Conduct is based on PyCon's and we need to review it and adapt the procedures of handling harassment. 

Reference: https://us.pycon.org/2015/about/code-of-conduct/

**Comment by kevindaum** [comment]
Do you still want/need attention on this?

**Comment by jefftriplett** [comment]
Hey Kevin, we have made some changes to ours over the past month and I want to actually step through what happens and how we should respond in case of an incident. Here is what we have: https://2015.djangocon.us/code_of_conduct/ -- I'm definitely open to feedback and improvements.

**Comment by williln** [comment]
A couple of resources in [this Twitter thread](https://twitter.com/betsythemuffin/status/601936839667224576).

**Comment by williln** [comment]
See also: The "internal" communication of the CoC for conference staff at the [Geek Feminism wiki](http://geekfeminism.wikia.com/wiki/Conference_anti-harassment/Policy), in particular: 

> Any member of conference staff can issue a verbal warning to a participant that their behavior violates the conference's anti-harassment policy. Warnings should be reported to [insert email address/phone number/etc. here] as soon as practical. The report should include:
- Identifying information (name/badge number) of the participant
- The time you issued the warning
- The behavior that was in violation
- The approximate time of the behavior (if different than the time of warning)
- The circumstances surrounding the incident
- Your identity
- Other people involved in the incident

Also: 

> Taking reports
> When taking a report from someone experiencing harassment you should record what they say and reassure them they are being taken seriously, but avoid making specific promises about what actions the organizers will take. Ask for any other information if the reporter has not volunteered it (such as time, place) but do not pressure them to provide it if they are reluctant. Even if the report lacks important details such as the identity of the person taking the harassing actions, it should still be recorded and passed along to the appropriate staff member(s). If the reporter desires it, arrange for an escort by conference staff or a trusted person, contact a friend, and contact local law enforcement. Do not pressure the reporter to take any action if they do not want to do it. Respect the reporter's privacy by not sharing unnecessary details with others, especially individuals who were not involved with the situation or non-staff members.

>Expulsion
>A participant may be expelled by the decision of any of the above listed entities for whatever reasons they deem sufficient. However, here are some general guidelines for when a participant should be expelled:
- A [first/second/third/seventeenth] offense resulting in a warning from staff
- Continuing to harass after any "No" or "Stop" instruction
- A pattern of harassing behavior, with or without warnings
- A single serious offense (e.g., punching or groping someone)
- A single obviously intentional offense (e.g., taking up-skirt photos)

**Comment by williln** [comment]
Change I would make to our CoC: 

> Remember that sexist, racist, and other exclusionary jokes can be offensive to those around you.  

to 

> Sexist, racist, and other exclusionary jokes are offensive, and are not acceptable at DjangoCon. 

and 

> If the matter is especially urgent, please call/contact any of these individuals:

Include the following: 

- Phone number 
- Email address
- Twitter handle 

Also make it clear that they can tweet at the DjangoCon twitter account, or use the "Contact us" link, both of which will be monitored throughout the conference.

**Comment by ossanna16** [comment]
+1 for everything Lacey mentioned.

A couple of suggestions:
- If I read correctly so far our CoC doesn't mention physical violations (only verbal ones, or display of sexual material etc.) Maybe we should add that?
- Does the CoC only apply for the time people are present at the conference or also for what happens outside of the conference, like dinners, conference parties etc.? I know at Django Under the Hood there was a pretty bad incident which happened at the hotel in the evening which was reported to the CoC team.
- It would be important to have at least one male and one female contact person available (in different ways: Twitter, email, phone call etc.) at all times. So far the CoC only mentions Jeff's number and a number to reach a DEFNA board member (it's not specified if this person is male or female).
- Maybe we could also add a safe place that people can go to to our CoC?
- We should definitely think about having some internal rules about which CoC violations lead to which kind of actions on our side. 
- All conference staff should be familiar with what to do in case of a CoC violation.

**Comment by williln** [comment]
Re: does our CoC mention physical violations?

> ... deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention.

But that could be clearer, I agree. 

Re: Does the CoC apply outside the conference; yes. 

> Accordingly, all attendees are expected to show respect and courtesy to other attendees throughout the conference and at all conference events, whether officially sponsored by DjangoCon or not.

Re: multiple people to report to. I agree! I will be a report-to person, but my info isn't up there yet. I need to see about getting a Google Voice number, as I'm not comfortable having my actual number up there. 

+1 on your other comments, too. I made a Trello card, and developing internal rules and reporting procedures, and training all conference staff on how to implement them, are on it.

**Comment by ossanna16** [comment]
Thank you, Lacey! :)

At EuroPython last year people used a special cell phone provided by the conference organizers to answer CoC calls. It would be fairly cheap to get one of those prepaid cell phones if we wanted to do this.

**Comment by craigbruce** [comment]
>So far the CoC only mentions Jeff's number and a number to reach a DEFNA board member (it's not specified if this person is male or female).

The DEFNA board member is a google voice number that will ring Jeff, Stacey and myself. Not sure we can guarantee who will answer first. Probably best being the third option.

**Comment by jefftriplett** [comment]
I added my google voice as a starting point. Randomly thoughts:

- I'm a little worried about harassment / potential for abuse so we should make a point of having any numbers listed here by a Google Voice number so the number isn't a permanent number. I'm throwing out GV because they are free and easy to work with.
- Distinct female contact number. 
- Organizer's contact number (DEFNA and probably mine but maybe DEFNA is fine).

**Comment by kevindaum** [comment]
Have you thought about having registrants sign the CoC when they register online and/or when they arrive at the event?

**Comment by craigbruce** [comment]
I've not heard of that before, definitely an interesting idea because as a speaker I've had to agreed to CoC before but not an attendee.

**Comment by ossanna16** [comment]
I like the idea! We could ask attendees to sign the CoC when they pick up their badges.

**Comment by jefftriplett** [comment]
It's a great idea. My preference is to make people agree to the CoC as part of buying a ticket which I looked into. At the time, it made sense like Craig said, if we are going to have speakers agree then we should ask everyone. 

I tried to set it up with Eventbrite's registration system and there was no way to make it required or part of the first screen. The option showed up on the second screen and it was easy to skip. 

I'm :+1: adopting the requirement but I'm concerned that it's going to be logistically a nightmare to track 300 pieces of paper at the event. However, this does bring up the point that we do not have the CoC referenced on our registration page or the Eventbrite page itself which we need to fix.

**Comment by williln** [comment]
> However, this does bring up the point that we do not have the CoC referenced on our registration page or the Eventbrite page itself which we need to fix.

I can add a link to the CoC from the registration page, maybe saying, 

> By registering for DjangoCon, you agree to abide by the Code of Conduct at all events, whether officially sponsored by the conference or not.

**Comment by jefftriplett** [comment]
Great, I'll add it to Eventbrite now too. :+1:

**Comment by ossanna16** [comment]
Awesome :) What about the people who already registered? Do we make them aware of it somehow?

**Comment by williln** [comment]
Added link and language directly below registration link on registration page. 

Per @ossanna16: maybe an email? "Thank you for registering! We want you to feel comfortable and proud to attend DjangoCon, so please review our Code of Conduct and know that all attendees will be expected to abide by it."

**Comment by ossanna16** [comment]
Sounds good!

**Comment by jefftriplett** [comment]
We'll shoot everyone an email too before the conference and we can add similar language as a reminder too.

[x] Eventbrite updated.
