### ISSUE TITLE
Sponsorship email?

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon-us-docs#26]
Can I get an email address forwarded to pete@lincolnloop.com? Something like sponsors@djangocon.us would be great.

**Comment by jefftriplett** [comment]
No problem. I cc'ed you in on my email to Jannis who will get it setup. I'll close this after we hear back.

**Comment by jefftriplett** [comment]
Done! One weird caveat in case you use Google Mail for your domain is that when you send an email to the forwarder you will not see a copy in your inbox even though it will go through. It makes testing them rather annoying unless you don't host through Google.
