### ISSUE TITLE
Obtain letter of invitation

### ISSUE THREAD

**Issue by craigbruce** [djangocon/djangocon-us-docs#27]
For oversea attendees a letter of invitation is required to aid with visa applications.

This is normal for conferences. PyCon makes reference to one at the bottom of https://us.pycon.org/2014/venue/traveling/

It would be good for us to obtain a copy of this from a PyCon friend

**Comment by jefftriplett** [comment]
I contacted Diane Clarke and Rami Chowdhury about how this is processed for PyCon and it's a bit more involved that I first thought. I'll take a look tonight but we might need a private repo to track.

**Comment by jefftriplett** [comment]
I have most of the process done. Just some legal / infrastructure to take care of.
