### ISSUE TITLE
"Reboot" announcement

### ISSUE THREAD

**Issue by ipmb** [djangocon/djangocon-us-docs#30]
On the last call @jacobian and @jefftriplett discussed writing a letter to describe what DEFNA is and distance ourselves from the previous organizers.

This would really help me in my efforts soliciting sponsors. Here's some of the feedback I've received from previous sponsors:

>  I've had some growing reservations about the conference over the past several years and have reduced our involvement as a result.  In addition, I'm wary about the cost-benefit ratio for us.

---

> ...there's some fatigue from lack of ROI for last year's investment. Once sponsors start jumping in it'll be easier for me to make the case internally that this is going to be far different from past events.

I know everyone is busy, but if there's any way this can be prioritized, I'd really appreciate it.

**Comment by jefftriplett** [comment]
I'll bump it back up to the top. I submitted it for approval last week and the first half was given a thumbs up whereas the second half was rejected. You are right though and it's been too long in the works and always seems to be the "next most important thing." I will make everything else wait and work on it right now.

**Comment by freakboy3742** [comment]
The DSF and DEFNA are currently working on the final language for the DjangoCon US licensing agreement; once that language is finalised and the contract is signed, I'm happy to publish a blog post on the DSG blog announcing the changing of the guard. We're probably a week or two away from having all the paperwork in place, though.

**Comment by jefftriplett** [comment]
I think this is a good balance of what helps Peter with sponsorship now and lets the DSF follow up later with specific details which pertain to the DSF and the Django community. Let me know if you see anything and I'll do an update or make corrections: https://2015.djangocon.us/blog/2015/04/07/new-year-new-djangocon-us/
