### ISSUE TITLE
Sprint venue questionnaire

### ISSUE THREAD

**Issue by craigbruce** [djangocon/djangocon-us-docs#32]
https://docs.google.com/forms/d/17-A2qH1G_Cl2Dg9hynqghq3rh9lGbbUhghFi0pEqNt8/viewform

Please review the questions for prospective sprint venue. Multiple companies have already offered space and it would be good to collate all the offers to make a decision.

**Comment by williln** [comment]
Since we're doing the DjangoGirls workshop on Day 1 of Sprints, can we add in a question about having a second space for about 50 people? cc @jefftriplett

**Comment by jefftriplett** [comment]
:+1:

**Comment by jefftriplett** [comment]
CC @mechanicalgirl and @kcunning

**Comment by craigbruce** [comment]
Good catch! I've added an extra field and made it clear two rooms are required for day one.

**Comment by williln** [comment]
There's usually an installation party the night before, so we could either
do the workshop on day 2 and the install party the night of day 1, or get
access to the venue on the last day of the conference and do the install
party the night of day 0, with the workshop on day 1. Don't want to over
implicate your form, we just haven't settled 100% on a workshop schedule.
cc @mechanicalgirl

(Sorry for all the date confusion! Barbara and I became co-organizers of
the workshop this weekend, and our ducks are not yet in a row.)

**Comment by crccheck** [comment]
Having gone to many sprints with networking headaches, I think Internet capabilities should be its own field.

**Comment by jefftriplett** [comment]
@craigbruce s/provider/provide from @kurol on irc.

**Comment by crccheck** [comment]
I'm not sure what the audience for this link is, but if it's getting viewed by organizations, they may not be familiar with djangocon or sprints. A sentence or two describing sprints would be helpful. Basically the info on https://2015.djangocon.us/sprints/ or linking to it.

**Comment by jefftriplett** [comment]
@williln No rush and thank you for helping to organize :) 

@crccheck Thank you for the feedback Chris. Adding a few sentences and a link back to the Sprint page is a great idea. 

My thoughts are that we should post a blog entry on the DjangoCon US website + Twitter account then point to the Sprint page with a link to this survey. We just want to dot the i's and cross the t's before we announce it.

**Comment by SHayslerSF** [comment]
Catering! 

"Sprint hosts typically provide a morning and afternoon coffee break, and a working lunch. Please describe your proposed catering arrangements."

Not sure if DjangoGirls is managing their own catering, or if that's something to ask of the hosts.

**Comment by williln** [comment]
DG was hoping to piggyback off of the catering for the sprints :)

**Comment by craigbruce** [comment]
@SHayslerSF, @jefftriplett, @crccheck, @kurol, @freakboy3742 Thank you all for your feedback. Hopefully I've captured everything.

@williln can you provide me one-liner about the installation party? E.g. approximate start/finish time, number of people, catering etc?

**Comment by jefftriplett** [comment]
One more minor thing that stuck out: 

![](https://www.evernote.com/shard/s27/sh/c967c7cc-fb49-4648-a42f-1d706cf66fd8/3f6d4d901f3f121c991dc171c63bb7ee/deep/0/DjangoCon-US-2015-Sprints-Workshop-Venue-Proposal.png)

**Comment by craigbruce** [comment]
@jefftriplett fixed

**Comment by jefftriplett** [comment]
This is all from @freakboy3742's email and the important bits that I want to make sure we don't miss. I'll open another ticket for the copy bits and I'll queue it up to work on.

> My suggestion with this form would be to be a little more explicit about requirements, so potential hosts know what you're looking for. In the past, some potential hosts thought the event was like an "after work drink-up" - so their facility is standing room for 100 for a couple of hours, not working space for 100 for 2 days. 

> I'd suggest the core requirements are:

>  * Capacity. Is it in one room or multiple? A single big room works better, but being split over 2 or 3 smaller rooms isn't the end of the world.
>  * Chairs, Tables
>  * Power - specially, power boards. And not "1 outlet per person" either - 3 or 4 per person, because power bricks usually mean you can't use every second outlet, and people want to charge their phones, etc.
>  * Whiteboards and projection facilities are nice to haves, but not core requirements.
>  * Security - do they need to have someone monitoring the event? Are people allowed to walk around unescorted? 
>  * Bathroom facilities - Are there enough of them? Can people get to/from the sprint room/rooms without escort? Will they be cleaned during the sprint (100 people generate a *lot* of paper towel waste - if the cleaning staff aren't emptying bins, the mens room goes feral pretty quickly).
>  * Transport - Is it a short walk from the conference hotel, or a 30 minute drive?
>  * After hours access - we're usually there on Saturday, so how will people get in? Will this affect transport options?
>  * Catering restrictions - are you allowed to bring in food from outside, or do you have to use in-house catering?

> In the past, we've had about 1/3 of conference attendees remain for sprints - so if you're expecting attendance of 300, a room that can comfortably hold 100 is a good starting point. 

> One suggestion that would be a big improvement on past years would be to "sell" a $0 "sprint ticket" - even if you don't check the tickets at the door, it will give you a much better idea of what to cater for.

**Comment by mechanicalgirl** [comment]
My only issue is probably an obvious one:

>> Capacity. Is it in one room or multiple? A single big room works better, but being split over 2 or 3 smaller rooms isn't the end of the world.

If we're doing the Django Girls class in the same location, then we do need multiple rooms - the class should be in a separate room, somewhere at least semi-private.

**Comment by jefftriplett** [comment]
We will definitely find a dedicated venue or venues for the Django Girls workshop and the Django Sprints. I'll make sure everyone in this thread gets to see all available options. Also available here: https://trello.com/b/clNFh6O1/sprints

**Comment by williln** [comment]
I do think we could forego the night-before Installation Party. They didn't do one at Pycon and it turned out fine. We can instruct them to install before they come, or let coaches help out once they get there.

**Comment by mechanicalgirl** [comment]
>> I do think we could forego the night-before Installation Party.

Agreed - I've used some really detailed install instructions for classes in the past and had a pretty good outcome. If we do have some students that really want personal help with installation, we can always do something ad-hoc and meet at a coffee shop or something like that.

**Comment by freakboy3742** [comment]
... the talk of installation parties points out the one obvious things that I missed: 

 * Bandwidth. Lots of it. No - More than that. And then a bit more :-) 

 * Wifi. Is there a guest network? Will it be able to handle everyone having 3 devices (laptop, phone and tablet)? 

DjangoGirls "installation on the day" works fine - as long as there is bandwidth. If you're on a Mac, for example, you need to install XCode - which is a couple of gigs - or at least the developer tools, which is a couple hundred meg. Get 20 people doing that at once on a bad network, and you're going to have a bad time :-)

**Comment by craigbruce** [comment]
I've removed the installation party question and added one about guest wifi.

Multiple rooms is covered in the survey header, but Google Forms are not hugely flexible so the sprint page on the djangocon website will need to make that clear as well.
