### ISSUE TITLE
Inclusion docs aren't visible

### ISSUE THREAD

**Issue by drewbrew** [djangocon/djangocon-us-docs#48]
https://djangocon.github.io/djangocon-us-docs/docs/inclusion/

There's nothing there even though we have docs.

**Comment by jefftriplett** [comment]
Let's tie this to https://github.com/djangocon/djangocon-us-docs/issues/44

**Comment by jefftriplett** [comment]
@drewbrew I think it's semi-mostly working https://djangocon.github.io/djangocon-us-docs/
