### ISSUE TITLE
Write the CfP

### ISSUE THREAD

**Issue by jacobian** [djangocon/djangocon-us-docs#6]
![](http://media0.giphy.com/media/rl0FOxdz7CcxO/giphy.gif)

Inspiration:

- [PyCon 2015](https://us.pycon.org/2015/speaking/cfp/)
- [DjangoCon Europe 2015](http://2015.djangocon.eu/proposals/)
- [NodeConf 2015](https://github.com/nodeconf/US-CFP)

**Comment by jefftriplett** [comment]
I see this is closed. Are you finished with the Google Doc or was there more to be done?

**Comment by jefftriplett** [comment]
cc @kcunning  - I made some changes to the Google doc. Please review so we can get it up tomorrow.
